# Generated by Django 5.1.2 on 2024-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperLoader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isScrapperRunning', models.BooleanField(default=False)),
                ('isScrapperCompleted', models.BooleanField(default=False)),
                ('isScrapperFailed', models.BooleanField(default=False)),
                ('isScrapperPaused', models.BooleanField(default=False)),
                ('isScrapperResumed', models.BooleanField(default=False)),
                ('isScrapperStopped', models.BooleanField(default=False)),
                ('isScrapperStarted', models.BooleanField(default=False)),
            ],
        ),
    ]
