# Generated by Django 5.1.2 on 2024-12-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashbaord', '0002_remove_scrapperloader_isscrappercompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapperloader',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapperloader',
            name='scrapper_status',
            field=models.CharField(default='Running', max_length=100),
        ),
    ]
