# Generated by Django 5.1.2 on 2024-12-21 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('business_services', models.TextField()),
                ('business_phone', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(default='Not Called', max_length=50)),
                ('called', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leads',
                'indexes': [models.Index(fields=['business_phone'], name='user_dashbo_busines_b444a2_idx'), models.Index(fields=['user', 'status'], name='user_dashbo_user_id_9b7741_idx')],
            },
        ),
    ]
